export const FETCHING_USERS ='FETCHING_USERS'

export const  FETCHING_SINGLE_USER='FETCHING_SINGLE_USER'
export const RECEIVED_USERS ='RECEIVED_USERS'
export const RECEIVED_SINGLE_USER ='RECEIVED_SINGLE_USER'

export const APPEND_USER_TO_FRONT ='APPEND_USER_TO_FRONT'
 
export const CREATING_USER ='CREATING_USER'
export const CREATED_USER ='CREATED_USER'
export const DELETE_USER ='DELETE_USER';
export const UPDATE_USER ='UPDATE_USER'